from django import forms

class AlgorithmInputForm(forms.Form):
    Header_Length = forms.FloatField()
    Protocol_Type = forms.FloatField()
    Time_To_Live = forms.FloatField()
    Rate = forms.FloatField()
    fin_flag_number = forms.FloatField()
    syn_flag_number = forms.FloatField()
    rst_flag_number = forms.FloatField()
    psh_flag_number = forms.FloatField()
    ack_flag_number = forms.FloatField()
    ece_flag_number = forms.FloatField()
    cwr_flag_number = forms.FloatField()
    ack_count = forms.IntegerField()
    syn_count = forms.IntegerField()
    fin_count = forms.IntegerField()
    rst_count = forms.IntegerField()
    HTTP = forms.FloatField()
    HTTPS = forms.FloatField()
    DNS = forms.FloatField()
    Telnet = forms.FloatField()
    SMTP = forms.FloatField()
    SSH = forms.FloatField()
    IRC = forms.FloatField()
    TCP = forms.FloatField()
    UDP = forms.FloatField()
    DHCP = forms.FloatField()
    ARP = forms.FloatField()
    ICMP = forms.FloatField()
    IGMP = forms.FloatField()
    IPv = forms.FloatField()
    LLC = forms.FloatField()
    Tot_sum = forms.IntegerField(label='Tot sum')
    Min = forms.IntegerField()
    Max = forms.IntegerField()
    AVG = forms.FloatField()
    Std = forms.FloatField()
    Tot_size = forms.FloatField(label='Tot size')
    IAT = forms.FloatField()
    Number = forms.IntegerField()
    Variance = forms.FloatField()
